### ISSUE TITLE
"ERROR in ./src/vendor.ts" and "ERROR in ./src/main.ts"

### ISSUE THREAD

**Issue by LPalmito** [SekibOmazic/ngrx-auth-example#2]
Hey!

I've tried to launch the app as explained in the quick start, but when I tried `npm start`, I've got:

```
ERROR in ./src/vendor.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint/lib/tslint.js:26:44)
    at Object.lint (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint-loader/index.js:63:23)
    at Object.module.exports (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint-loader/index.js:151:8)

ERROR in ./src/main.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint/lib/tslint.js:26:44)
    at Object.lint (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint-loader/index.js:63:23)
    at Object.module.exports (/Users/yannick/Documents/dev/ngrx-auth-example/node_modules/tslint-loader/index.js:151:8)

webpack: bundle is now VALID.
```

I also encountered few problems when doing `npm install`, but it was OK with a `sudo npm install`.

Thank you for your help! :)

**Comment by aaroncalderon** [comment]
I'm having the same issue.

**Comment by khushbuparakh** [comment]
I am also having same issue. I tried everything but stuck on it since long need help?
